version: "3.8"

services:
  api:
    build: .
    container_name: api
    ports:
      - "3013:3012"
    env_file:
      - .env
    volumes:
      - ./apibd.db:/app/apibd.db
    command: npm start

  test:
    build: .
    container_name: api_test
    depends_on:
      - api
    volumes:
      - ./prisma/test.db:/app/prisma/dev.db
    command: npm test
